# Generated by Django 3.1.5 on 2021-07-21 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('state_abbrev', models.CharField(max_length=2)),
                ('number_crags', models.IntegerField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='userAccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=150)),
                ('l_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=30)),
                ('climber_type', models.CharField(choices=[('Trad', 'Trad Climber'), ('Sport', 'Sport Climber'), ('Ice', 'Ice Climber'), ('Boulderer', 'Boulderer'), ('Gym', 'Gym Climber')], default='Sport', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='weatherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_temp', models.IntegerField(max_length=3)),
                ('daily_high_temp', models.IntegerField(max_length=3)),
                ('daily_low_temp', models.IntegerField(max_length=3)),
                ('precip_ammount', models.FloatField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='cragModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crag_type', models.CharField(max_length=50)),
                ('crag_lattitude', models.FloatField(default=0.0, max_length=25)),
                ('crag_longitude', models.FloatField(default=0.0, max_length=25)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cragweather.statemodel')),
            ],
        ),
    ]
