# Generated by Django 3.1.5 on 2021-07-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cragweather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statemodel',
            name='number_crags',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weathermodel',
            name='current_temp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weathermodel',
            name='daily_high_temp',
            field=models.IntegerField(),
        ),
    ]
