# Generated by Django 3.1.5 on 2021-07-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cragweather', '0002_auto_20210721_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathermodel',
            name='daily_low_temp',
            field=models.IntegerField(),
        ),
    ]
