# Generated by Django 3.1.5 on 2021-07-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cragweather', '0003_auto_20210721_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='cragmodel',
            name='crag_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
