# Generated by Django 3.1.5 on 2021-07-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cragweather', '0004_cragmodel_crag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathermodel',
            name='day',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='weathermodel',
            name='month',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='weathermodel',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='cragmodel',
            name='crag_type',
            field=models.CharField(choices=[('Trad', 'Trad'), ('Sport', 'Sport'), ('Ice', 'Ice'), ('Boulder', 'Boulder')], default='-----', max_length=50),
        ),
    ]
