# Generated by Django 3.1.5 on 2021-07-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cragweather', '0005_auto_20210721_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='locationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('number_crags', models.IntegerField()),
                ('location_web_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='cragmodel',
            name='state',
        ),
        migrations.DeleteModel(
            name='stateModel',
        ),
    ]
