# Generated by Django 3.1.5 on 2021-07-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cragweather', '0008_remove_cragmodel_crag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cragmodel',
            name='crag_link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
